name: modular
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
#  - _libgcc_mutex=0.1=main
#  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - cryptography=37.0.2=py38h2b5fc30_0
#  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.3=pyhd8ed1ab_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
#  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
#  - libgcc-ng=11.2.0=h1234567_0
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
#  - libgomp=11.2.0=h1234567_0
#  - libiconv=1.17=h166bdaf_0
  - libllvm11=11.1.0=h9e868ea_6
  - libpng=1.6.37=h21135ba_2
#  - libstdcxx-ng=11.2.0=h1234567_0
  - libtiff=4.2.0=hf544144_3
  - libwebp-base=1.2.2=h7f98852_1
  - llvmlite=0.39.1=py38he621ea3_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - mpi=1.0=openmpi
  - mpi4py=3.1.4=py38h3e5f7c9_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.6=he412f7d_0
#  - numba=0.56.4=py38h417a72b_0
  - numpy-base=1.23.1=py38ha15fc14_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openmpi=4.0.4=hdf1f1ad_0
  - openssl=1.1.1s=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
#  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.13=h12debd9_0
  - python_abi=3.8=2_cp38
#  - pytorch=1.12.1=py3.8_cuda11.6_cudnn8.3.2_0
#  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.38.3=hc218d9a_0
  - tbb=2021.6.0=hdb19cb5_1
  - tk=8.6.11=h1ccaba5_1
  - typing_extensions=4.3.0=pyha770c72_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
#  - zstd=1.5.0=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - ale-py==0.7.5
    - alembic==1.7.7
    - attrdict==2.0.1
    - attrs==21.4.0
    - autopage==0.5.0
    - autorom==0.4.2
    - autorom-accept-rom-license==0.4.2
    - cachetools==5.1.0
    - cffi==1.15.1
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cliff==3.10.1
    - cloudpickle==2.1.0
    - cmaes==0.8.2
    - cmd2==2.4.1
    - colorlog==6.6.0
    - cycler==0.11.0
    - cython==0.29.30
    - fasteners==0.17.3
    - fonttools==4.33.3
    - glfw==2.5.3
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - greenlet==1.1.2
    - grpcio==1.46.3
    - gym==0.23.0
    - gym-notices==0.0.8
    - gym-robotics==0.1.0
    - hausdorff==0.2.6
    - imageio==2.19.5
    - importlib-metadata==4.11.4
    - importlib-resources==5.7.1
    - joblib==1.2.0
    - kiwisolver==1.4.2
    - mako==1.2.0
    - markdown==3.3.7
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - mujoco-py==2.1.2.14
    - numpy==1.22.4
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - optuna==2.10.0
    - packaging==21.3
    - panda-gym==2.0.4
    - pandas==1.4.2
    - pbr==5.9.0
    - pillow==9.1.1
    - prettytable==3.3.0
    - protobuf==3.20.1
    - psutil==5.9.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybullet==3.2.5
    - pyparsing==3.0.9
    - pyperclip==1.8.2
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sb3-contrib==1.5.1a5
    - scikit-learn==1.1.3
    - scipy==1.8.1
    - seaborn==0.11.2
    - sklearn==0.0.post1
    - soyclustering==0.2.0
    - sqlalchemy==1.4.36
    - stable-baselines3==1.6.0
    - stevedore==3.5.0
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
#    - torch==1.11.0
#    - torchaudio==0.11.0
#    - torchvision==0.12.0
    - tqdm==4.64.0
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - wcwidth==0.2.5
    - werkzeug==2.1.2
    - zipp==3.8.0
prefix: /home/pj81/anaconda3/envs/modular
